In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.read_csv("../data/tb_cust.csv")
transactions = pd.read_csv("../data/tb_transaction.csv")
products = pd.read_csv("../data/tb_transaction_product.csv")
fees = pd.read_csv("../data/tb_transaction_fees.csv")

In [3]:
print("Customers:", customers.shape)
print("Transactions:", transactions.shape)
print("Products:", products.shape)
print("Fees:", fees.shape)

Customers: (10000, 6)
Transactions: (200000, 5)
Products: (200000, 4)
Fees: (200000, 4)

In [4]:
display(customers.head())
display(transactions.head())
display(products.head())
display(fees.head())

,customer_id,customer_name,age,customer_segment,city,registration_date
0,1,Joko Pratama,24,College Student,Makassar,2026-02-03
1,2,Lina Pratama,25,Office Worker,Pekanbaru,2025-01-06
2,3,Dina Sari,23,Office Worker,Jakarta,2025-03-22
3,4,Gita Nugraha,22,College Student,Bandung,2025-07-08
4,5,Fajar Saputra,18,High School Student,Palembang,2025-01-28

,transaction_id,customer_id,transaction_date,transaction_type,amount
0,65729,3302,2025-01-01 00:00:00,Bank Transfer,271040.36
1,100855,8069,2025-01-01 00:00:00,Bank Transfer,389439.44
2,43254,4752,2025-01-01 00:00:00,Shopping Payment,74162.57
3,43050,6521,2025-01-01 00:00:00,Bank Transfer,141149.29
4,46190,1833,2025-01-01 00:00:00,Shopping Payment,696860.92

   transaction_product_id  transaction_id       product_name product_category
0                       1           65729      Food Delivery             Food
1                       2          100855    Online Shopping       E-Commerce
2                       3           43254              Other            Other
3                       4           43050      Mobile Top Up    Digital Goods
4                       5           46190  Education Payment        Education

   fee_id  transaction_id  fee_percentage  fee_amount
0       1           65729             0.5     1355.20
1       2          100855             0.5     1947.20
2       3           43254             1.0      741.63
3       4           43050             0.5      705.75
4       5           46190             1.0     6968.61

In [5]:
print("=== CUSTOMERS ===")
customers.info()

print("\n=== TRANSACTIONS ===")
transactions.info()

print("\n=== PRODUCTS ===")
products.info()

print("\n=== FEES ===")
fees.info()

=== CUSTOMERS ===

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        10000 non-null  int64
 1   customer_name      10000 non-null  object
 2   age                10000 non-null  int64
 3   customer_segment   10000 non-null  object
 4   city               10000 non-null  object
 5   registration_date  10000 non-null  object
dtypes: int64(2), object(4)
memory usage: 468.9+ KB

=== TRANSACTIONS ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    200000 non-null  int64
 1   customer_id       200000 non-null  int64
 2   transaction_date  200000 non-null  object
 3   transaction_type  200000 non-null  object
 4   amount            200000 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 7.6+ MB

=== PRODUCTS ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 4 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   transaction_product_id  200000 non-null  int64
 1   transaction_id          200000 non-null  int64
 2   product_name            200000 non-null  object
 3   product_category        200000 non-null  object
dtypes: int64(2), object(2)
memory usage: 6.1+ MB

=== FEES ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   fee_id          200000 non-null  int64
 1   transaction_id  200000 non-null  int64
 2   fee_percentage  200000 non-null  float64
 3   fee_amount      200000 non-null  float64
dtypes: float64(2), int64(2)
memory usage: 6.1 MB

In [6]:
print("=== MISSING VALUES ===")

print("\nCustomers:")
print(customers.isnull().sum())

print("\nTransactions:")
print(transactions.isnull().sum())

print("\nProducts:")
print(products.isnull().sum())

print("\nFees:")
print(fees.isnull().sum())

=== MISSING VALUES ===

Customers:
customer_id          0
customer_name        0
age                  0
customer_segment     0
city                 0
registration_date    0
dtype: int64

Transactions:

transaction_id      0
customer_id         0
transaction_date    0
transaction_type    0
amount              0
dtype: int64

Products:
transaction_product_id    0
transaction_id            0
product_name              0
product_category          0
dtype: int64

Fees:
fee_id            0
transaction_id    0
fee_percentage    0
fee_amount        0
dtype: int64

In [7]:
print("=== DUPLICATES ===")

print("Customers:", customers.duplicated().sum())
print("Transactions:", transactions.duplicated().sum())
print("Products:", products.duplicated().sum())
print("Fees:", fees.duplicated().sum())

=== DUPLICATES ===
Customers: 0
Transactions: 0
Products: 0
Fees: 0